<a href="https://colab.research.google.com/github/MauryaAG07/Learning-and-practice/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cupy as cp
import numpy as np
array_cpu = np.random.randint(0, 255, size = (4000,4000))
array_cpu.nbytes/1e6

128.0

In [2]:
array_gpu = cp.asarray(array_cpu)

In [3]:
%%timeit
cp.asarray(array_cpu)

59.8 ms ± 30 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
type(array_gpu)

cupy.ndarray

In [5]:
from scipy import fft

In [6]:
%%timeit
fft.fft(array_cpu)

540 ms ± 137 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
from cupyx.scipy import fft as fft_gpu

In [8]:
%%timeit
fft_gpu.fftn(array_gpu)

181 µs ± 79.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:

fft_cpu = fft.fftn(array_cpu)
fft_sent_back = cp.asnumpy(fft_gpu.fftn(array_gpu))
np.allclose(fft_sent_back, fft_cpu)

True

In [10]:
np.max(array_gpu)


array(254)

In [11]:
type(np.max(array_gpu))

cupy.ndarray

In [12]:
cp.random.randint(0,255, size=(4000,4000))

array([[ 41, 173, 109, ..., 206,  32,  31],
       [127, 131,   1, ...,  54, 211, 125],
       [ 43,  98, 116, ..., 121, 198,  18],
       ...,
       [205,  80,  44, ...,  70, 135,  91],
       [ 96,  96,  23, ...,  46,  99, 224],
       [ 83, 167, 127, ..., 199,  60,  84]])

It is much faster to generate arrays in the gpu vs cpu.

In [13]:
from numba import cuda

In [14]:
cuda.detect()

Found 1 CUDA devices
id 0                Tesla T4                              [SUPPORTED]
                      Compute Capability: 7.5
                           PCI Device ID: 4
                              PCI Bus ID: 0
                                    UUID: GPU-b07f01ad-626a-517b-445d-456234b58d7c
                                Watchdog: Disabled
             FP32/FP64 Performance Ratio: 32
Summary:
	1/1 devices are supported


True

In [15]:
cpu_array = np.random.randint(0,10, size=(2000,2000))

In [18]:
d_array = cuda.to_device(array_cpu)
d_array

In [19]:
cp.asarray(d_array)

array([[ 78, 209, 212, ...,   7,  36, 150],
       [  6, 184, 173, ...,  74, 251,  25],
       [189,  94, 200, ..., 225,  32, 136],
       ...,
       [154, 250, 231, ..., 237, 242, 248],
       [ 63,  90,  42, ...,  89,  84, 202],
       [168, 181, 246, ..., 249, 203, 215]])

In [21]:
d_array.copy_to_host()

array([[ 78, 209, 212, ...,   7,  36, 150],
       [  6, 184, 173, ...,  74, 251,  25],
       [189,  94, 200, ..., 225,  32, 136],
       ...,
       [154, 250, 231, ..., 237, 242, 248],
       [ 63,  90,  42, ...,  89,  84, 202],
       [168, 181, 246, ..., 249, 203, 215]])